/**
 * AuditEvent — frozen-set persisted event shape.
 *
 * See doc/04-shared-vocabulary.md § AuditEvent for the canonical spec.
 *
 * `action` and `AuditResource.kind` are open string unions: well-known
 * values get autocomplete; consumers extend the set without an API
 * bump. `outcome`, `severity`, and `AuditActor.kind` are closed —
 * they shape persistence and require an RFC to extend.
 */

import type { TenantId } from "./tenant.js";

/** JSON value shape; what's safely round-trippable through DynamoDB / JSON. */
export type JsonPrimitive = string | number | boolean | null;

export interface JsonObject {
  readonly [key: string]: JsonValue;
}

export type JsonArray = ReadonlyArray<JsonValue>;

export type JsonValue = JsonPrimitive | JsonObject | JsonArray;

/** Closed: extending requires an RFC. Shapes persistence. */
export type AuditSeverity = "info" | "warning" | "error";

/** Closed: extending requires an RFC. Shapes alerting and retention queries. */
export type AuditOutcome = "success" | "failure";

/**
 * Open string union. Well-known actions get autocomplete; consumers
 * extend with their own values without bumping the type.
 */
export type AuditAction =
  | "auth.login"
  | "auth.logout"
  | "auth.federated_link"
  | "idp.create"
  | "idp.update"
  | "idp.delete"
  | "data.read"
  | "data.create"
  | "data.update"
  | "data.delete"
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type -- intentional open-union sentinel
  | (string & {});

/** Closed: the four cases exhaust meaningful provenance. New kind requires RFC. */
export type AuditActor =
  | {
      readonly kind: "user";
      readonly userSub: string;
      /** Set for federated logins; absent for native Cognito sign-ins. */
      readonly idp?: {
        readonly providerName: string;
        readonly providerType: "OIDC" | "SAML";
      };
    }
  | { readonly kind: "service"; readonly serviceName: string }
  | { readonly kind: "system"; readonly component: string }
  | { readonly kind: "anonymous" };

export interface AuditResource {
  /** Open string union: conventions per consumer (e.g., "user", "secret"). */
  readonly kind: string;
  readonly id: string;
}

/**
 * The persisted audit-event shape. Frozen because changing a field
 * here forces a migration of every prior row.
 */
export interface AuditEvent {
  /** ulid; ordered, sortable. Generated by foundation, not consumer-supplied. */
  readonly id: string;
  /** ISO 8601, UTC, ms precision. */
  readonly timestamp: string;
  /** Absent for cross-tenant events (e.g., system-level operations). */
  readonly tenantId?: TenantId;
  readonly actor: AuditActor;
  readonly action: AuditAction;
  readonly resource?: AuditResource;
  readonly outcome: AuditOutcome;
  /** Populated iff outcome === 'failure'. */
  readonly failureReason?: string;
  readonly severity: AuditSeverity;
  /** Links to RequestContext.requestId. */
  readonly requestId?: string;
  /** Distributed tracing identifier. */
  readonly traceId?: string;
  /** Already scrubbed if region policy requires (foundation/src/net/ip-scrubber). */
  readonly ipAddress?: string;
  /** Full-fidelity — UA mismatch is a security signal. */
  readonly userAgent?: string;
  /** Consumer-controlled extension point. JSON-round-trippable only. */
  readonly metadata?: Readonly<Record<string, JsonValue>>;
}
